name: CI

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: tododb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Ajustado para o seu caminho real: unifacema-tde-devops/unifacema-tde-devops.csproj
    - name: Restore dependencies
      run: dotnet restore unifacema-tde-devops/unifacema-tde-devops.csproj

    - name: Build
      run: dotnet build unifacema-tde-devops/unifacema-tde-devops.csproj --no-restore

    # Se você tiver o projeto de testes na raiz ou em outra pasta, ajuste aqui:
    - name: Test
      run: dotnet test TodoApi.Tests/TodoApi.Tests.csproj --no-build --verbosity normal

    - name: Build Docker Image
      run: |
        # O Dockerfile está dentro da subpasta unifacema-tde-devops/
        docker build -t todo-api:latest ./unifacema-tde-devops
