name: CI

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: tododb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # 1. Restore: Usando curingas para achar todos os projetos (API e Testes)
    - name: Restore dependencies
      run: dotnet restore

    # 2. Build: Compila a solução inteira de uma vez
    - name: Build
      run: dotnet build --no-restore

    # 3. Test: O segredo é remover o --no-build para ele garantir que tudo está pronto
    - name: Test
      run: dotnet test --verbosity normal

    # 4. Docker Build: Mantendo o caminho que funcionou para o seu Dockerfile
    - name: Build Docker Image
      run: |
        docker build -t todo-api:latest -f unifacema-tde-devops/Dockerfile .